### ISSUE TITLE
GraalVM Native Image build support

### ISSUE THREAD

**Issue by YunaBraska** [rife2/bld#25] opened 2024-04-04 12:29 UTC
I am currently also go back to the root of java instead of tools and frameworks.
I like to build native executables with graalvm.
Would be really nice to be able to build native executables with `bld`.

_Maybe bld could be also build with graalvm so you don't need even java to execute it but no idea if this makes sense_

**Comment by gbevin** [comment] 2024-04-04 12:45
That's a great idea, it definitely seems within the realm of possibilities with a dedicated extension

**Comment by ethauvin** [comment] 2024-04-04 12:59
One could write a simple extension that executes something like:

```console
native-image [options] -jar jarfile [executable name]
```

Would that work for you, @YunaBraska?

**Comment by ethauvin** [comment] 2024-04-04 13:42
You could also use the [bld-exec](https://github.com/rife2/bld-exec) extension:

```java
@BuildCommand(value = "native-exec", summary = "Build a native executable")
public void nativeExec() throws Exception {
  new ExecOperation()
        .fromProject(this)
        .command("native-image", "-jar",  
             Paths.get(buildDirectory.getAbsolutePath(), jarFileName))
        .execute();
}
```

```console
./bld compile jar native-exec
```

I haven't actually tested it, so the code might need some cleanup.

**Comment by YunaBraska** [comment] 2024-04-04 13:52
Nice fallback option, but I would like to have something more type safe in which I can just configure the native image. There are some more options than just build a native image and i have no idea how the original command even looks like since I use just the maven plugin like this: 

```
<profile>
         <id>native-image</id>
         <build>
             <plugins>
                 <plugin>
                     <groupId>org.graalvm.nativeimage</groupId>
                     <artifactId>native-image-maven-plugin</artifactId>
                     <version>21.2.0</version>
                     <configuration>
                         <imageName>ExampleApp</imageName>
                         <mainClass>de.yuna.berlin.nativeapp.ExampleApp</mainClass>
                         <buildArgs>
                             <!-- Reduces the image size - Ensures the native image doesn't include the JVM as a fallback option -->
                             <buildArg>--no-fallback</buildArg>
                             <!-- Disables the use of the GraalVM compilation server -->
                             <buildArg>--no-server</buildArg>
                             <!-- Improve startup time - Initialize classes at build time rather than at runtime -->
                             <buildArg>--initialize-at-build-time</buildArg>
                             <!-- Include all files under /resources -->
                             <buildArg>-H:IncludeResources=resources/config/.*</buildArg>
                         </buildArgs>
                     </configuration>
                     <executions>
                         <execution>
                             <goals>
                                 <goal>native-image</goal>
                             </goals>
                             <phase>package</phase>
                         </execution>
                     </executions>
                 </plugin>
             </plugins>
         </build>
     </profile>
```

**Comment by ethauvin** [comment] 2024-04-04 14:14
All the native-image options are here:

* https://www.graalvm.org/22.0/reference-manual/native-image/Options/

Looking at your maven configuration, you can just pass the `buildArgs` to the bld-exec `command`.

Something like:

```java
.command("native-image",
    "--no-fallback",
    " --no-server",
    "--initialize-at-build-time",
    "-H:IncludeResources=" + srcMainResourcesDirectory.getAbsolutePath(),
    "de.yuna.berlin.nativeapp.ExampleApp",
    "ExampleApp")
```

Pretty straight forward.

**Comment by ethauvin** [comment] 2024-04-04 17:02
@YunaBraska I've created a full working example:

* https://github.com/rife2/graalvm-native-bld-example

**Comment by YunaBraska** [comment] 2024-04-05 05:58
Thanks, I can see that. Looks nice, but I would like to have it more declarative and type safe. So that I don't invent some random parameters and maybe also have some verifications.

**Comment by ethauvin** [comment] 2024-04-05 06:33
> Thanks, I can see that. Looks nice, but I would like to have it more declarative and type safe. So that I don't invent some random parameters and maybe also have some verifications.

It's no less type-safe than the Maven example you provided. If you use an invalid parameter, you'll get an error, just like Maven.

If you build an extension, you could have each parameter mapped to a function, and do all kind of validation. Frankly, that's a lot of work for very little benefit.

bld is not declarative by design.

**Comment by ethauvin** [comment] 2024-05-22 10:43
I'm going to close this issue for now. 

If you ever felt like working on an extension, let me know, I'll try to help.

**Closed** 2024-05-22 10:43 UTC
